services:
  moq:
    build:
     context: ./moq
     dockerfile: Dockerfile
    ports:
      - "8081:3000"
    restart: always
    networks:
      - net

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru_RU "
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgres/data
    networks:
      - net

  identity:
    build:
      context: .
      dockerfile: ./identity.api/Dockerfile
      args:
        configuration: "Debug"
    ports:
      - "5096:80"
      - "7255:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
    restart: always
    volumes:
      - ${HOME}/.aspnet/dev-certs/trust:/https/
    depends_on:
      - postgres
    networks:
      - net

  catalog:
    build:
      context: .
      dockerfile: ./catalog.api/Dockerfile
      args:
        configuration: "Debug"
    ports:
      - "5207:80"
      - "7259:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
    restart: always
    volumes:
      - ${HOME}/.aspnet/dev-certs/trust:/https/
    depends_on:
      - identity
    networks:
      - net

  frontend:
    build:
     context: ./eshop
     dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always
    networks:
      - net

networks:
  net:
    name: angular-network